# Generated by Django 2.2 on 2020-03-29 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0002_auto_20200319_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
