# Generated by Django 2.2 on 2020-03-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='emailContacto',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='metodoContacto',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='numeroContacto',
        ),
    ]
