# Generated by Django 2.2 on 2020-03-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0002_auto_20200308_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donante',
        ),
    ]
