# Generated by Django 2.2 on 2020-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0004_donante'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='departamento',
            field=models.CharField(choices=[('Montevideo', 'Montevideo'), ('Artigas', 'Artigas'), ('Canelones', 'Canelones')], default='MO', max_length=30),
        ),
    ]
