# Generated by Django 2.2 on 2020-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0005_donante_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='grupoSanguineo',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('DESCONOCIDO', 'Desconocido')], default='DESC', max_length=11),
        ),
    ]
