# Generated by Django 2.2 on 2020-03-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0006_auto_20200312_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='departamento',
            field=models.CharField(choices=[('Montevideo', 'Montevideo')], default='MO', max_length=30),
        ),
        migrations.AlterField(
            model_name='donante',
            name='grupoSanguineo',
            field=models.CharField(choices=[('DESCONOCIDO', 'Desconocido'), ('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='DESC', max_length=11),
        ),
    ]
