# Generated by Django 2.2 on 2020-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0007_auto_20200313_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='departamento',
            field=models.CharField(choices=[('MO', 'Montevideo'), ('AR', 'Artigas'), ('CA', 'Canelones'), ('CL', 'Cerro Largo'), ('CO', 'Colonia'), ('DU', 'Durazno'), ('FS', 'Flores'), ('FR', 'Florida'), ('LA', 'Lavalleja'), ('MA', 'Maldonado'), ('PA', 'Paysandú'), ('RN', 'Rio Negro'), ('RI', 'Rivera'), ('RO', 'Rocha'), ('SA', 'Salto'), ('SJ', 'San José'), ('SO', 'Soriano'), ('TA', 'Tacuarembó'), ('TT', 'Treinta y Tres')], default='Montevideo', max_length=30),
        ),
    ]
