# Generated by Django 2.2 on 2020-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0008_auto_20200313_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='apellidos',
            field=models.CharField(default='Perez', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donante',
            name='emailContacto',
            field=models.EmailField(default='y@g.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donante',
            name='nombres',
            field=models.CharField(default='Juan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donante',
            name='numeroContacto',
            field=models.CharField(default='09988877', max_length=12),
            preserve_default=False,
        ),
    ]
