# Generated by Django 2.2 on 2020-03-29 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0010_auto_20200314_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donante',
            name='id',
        ),
        migrations.AlterField(
            model_name='donante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
